apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: hello
            - name: POSTGRES_USER
              value: hello
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.auth.password | quote }}
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "hello"]
            initialDelaySeconds: 5
            periodSeconds: 5
